
[functions.ai-design]
enabled = true
verify_jwt = true
import_map = "./functions/ai-design/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/ai-design/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/ai-design/*.html" ]

[functions.help-bot]
enabled = true
verify_jwt = false
entrypoint = "./functions/help-bot/index.ts"

[functions.pinterest-oembed]
enabled = true
verify_jwt = false
entrypoint = "./functions/pinterest-oembed/index.ts"

[functions.translate-comments]
enabled = true
verify_jwt = false
entrypoint = "./functions/translate-comments/index.ts"
